name: Build Docker image workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
 
  build-image:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      
      - name: Building image
        run: docker build -t ${{inputs.image-name}} .
