name: Build Docker image workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      account-id: 
        required: true
        type: string
      tag:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:

 
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building image
        run: docker build -t ${{inputs.image-name}} .
      - name: tag
        run: docker tag ${{inputs.image-name}} ${{inputs.account-id}}.dkr.ecr.${{inputs.aws-region}}.amazonaws.com/${{inputs.repository}}:${{inputs.tag}}
      - name: push
        run: docker push ${{inputs.account-id}}.dkr.ecr.${{inputs.aws-region}}.amazonaws.com/${{inputs.repository}}:${{inputs.tag}}