name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Provide auth credentials
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 693725700380.dkr.ecr.eu-west-1.amazonaws.com

    - name: Build the Docker image
      run: docker build -t nankov/node .
 

    - name: Tag image
      run: docker tag nankov/node  693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo
       
    - name: Push image to ECR
      run: docker push 693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo
  
    
    
