name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA2DBKGEEODSIZLYH5
        aws-secret-access-key: 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
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build the Docker image
      run: docker build -t nankov/node .
 

    - name: Tag image
      run: docker tag nankov/node  693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo:1
       
    - name: Push image to ECR
      run: docker push 693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo:1
  
    
    
