name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  #aditional permissions

jobs:

  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::693725700380:role/ECRWriteForActions
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

#    - name: Build tag and push image
#      uses: actions/nankov/push-to-ecr-action@v1
#      with:
#          image-name: nankov/node
#          tag: '1'
#          aws-region: eu-west-1
#          account-id: '693725700380'
#          repository: appstart-repo
    - run: docker build -t nankov/node .
    - run:  docker tag nankov/node 693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo:1
    - run: docker push 693725700380.dkr.ecr.eu-west-1.amazonaws.com/appstart-repo:1
 
          

  
    
    
